version: '3'
services:
  api:
    image: node:lts
    working_dir: /api
    platform: linux/amd64
    volumes:
      - .:/api:z
    entrypoint: ./entrypoint.sh
    depends_on:
      - db
    ports:
      - 3000:3000
    command: yarn dev
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: db_test
      DB_NAME: test
      AUTH_COOKIE_NAME: auth_cookie
      NEXT_PUBLIC_BASE_RSVP_URL: http://localhost:3000/rsvp
  db:
    image: mongo:4.4.6
    restart: always
    platform: linux/amd64
    volumes:
      - db-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: db_test
      MONGO_INITDB_DATABASE: test
volumes:
  db-data: